// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIcXsncD9K69us1Ka0nej0qKRH9G3cYjY',
    appId: '1:1082872494222:web:91001f49f86044a10831df',
    messagingSenderId: '1082872494222',
    projectId: 'flutter-chat-app-7d836',
    authDomain: 'flutter-chat-app-7d836.firebaseapp.com',
    storageBucket: 'flutter-chat-app-7d836.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCmZ0jW7Cf-r7mrjNhsGPu2-_9cmo14zw',
    appId: '1:1082872494222:android:acb1c7d3748944620831df',
    messagingSenderId: '1082872494222',
    projectId: 'flutter-chat-app-7d836',
    storageBucket: 'flutter-chat-app-7d836.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzOGxO8SMFNd-vZGhxTNY2lZC965F1o4Y',
    appId: '1:1082872494222:ios:23c6ae47c930c9500831df',
    messagingSenderId: '1082872494222',
    projectId: 'flutter-chat-app-7d836',
    storageBucket: 'flutter-chat-app-7d836.firebasestorage.app',
    iosClientId: '1082872494222-6bj7tdibdh8h6hcph5rr5e1c88adnufg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzOGxO8SMFNd-vZGhxTNY2lZC965F1o4Y',
    appId: '1:1082872494222:ios:23c6ae47c930c9500831df',
    messagingSenderId: '1082872494222',
    projectId: 'flutter-chat-app-7d836',
    storageBucket: 'flutter-chat-app-7d836.firebasestorage.app',
    iosClientId: '1082872494222-6bj7tdibdh8h6hcph5rr5e1c88adnufg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIcXsncD9K69us1Ka0nej0qKRH9G3cYjY',
    appId: '1:1082872494222:web:06c030a21bcf1a860831df',
    messagingSenderId: '1082872494222',
    projectId: 'flutter-chat-app-7d836',
    authDomain: 'flutter-chat-app-7d836.firebaseapp.com',
    storageBucket: 'flutter-chat-app-7d836.firebasestorage.app',
  );
}
